"""Synthetic data bias amplification detector.

Checks whether a synthetic dataset generated by a generative model (CTGAN,
TVAE, GaussianCopula, etc.) amplifies demographic biases present in the
original real training data.

Detection methodology:
1. KL Divergence — measures shift in protected attribute group distribution
   between real and synthetic data. High KL divergence indicates the generator
   has altered the demographic composition.
2. Label Rate Disparity — for each protected attribute group, compares the
   positive label rate in real vs synthetic data. Large differences indicate
   the generator has encoded different outcome rates per group.
3. Amplification Factor — computes disparate impact in both datasets and
   returns the ratio synthetic_di / real_di. A value > 1.0 indicates the
   synthetic data has more disparity than the real data (bias amplification).
   A value < 1.0 indicates the generator actually reduced existing bias.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from scipy.special import rel_entr  # type: ignore[import-untyped]

from aumos_common.observability import get_logger

logger = get_logger(__name__)


class SyntheticBiasAmplificationDetector:
    """Detects bias amplification in AI-generated synthetic datasets.

    Compares the demographic distribution and label rates between a real
    training dataset and a synthetic dataset generated from it, returning
    quantitative amplification metrics.
    """

    def check_amplification(
        self,
        real_features: list[dict[str, Any]],
        real_labels: list[int],
        synthetic_features: list[dict[str, Any]],
        synthetic_labels: list[int],
        protected_attribute: str,
    ) -> dict[str, Any]:
        """Check whether the synthetic dataset amplifies real-data bias.

        Computes three amplification signals and per-group statistics.
        All computation is synchronous. Call via asyncio.to_thread() in
        async service methods.

        Args:
            real_features: Feature dicts for the real training dataset.
            real_labels: Binary labels for the real dataset.
            synthetic_features: Feature dicts for the synthetic dataset.
            synthetic_labels: Binary labels for the synthetic dataset.
            protected_attribute: Column name of the protected attribute to analyse.

        Returns:
            Dict with keys:
                kl_divergence (float): KL divergence of group distributions.
                label_rate_disparity (float): Max absolute label rate difference
                    across groups between real and synthetic.
                amplification_factor (float): Disparate impact ratio in synthetic
                    divided by disparate impact ratio in real. > 1.0 means amplification.
                group_stats (list[dict]): Per-group aggregate statistics.
        """
        real_groups = self._extract_group_labels(
            features=real_features,
            labels=real_labels,
            protected_attribute=protected_attribute,
        )
        synthetic_groups = self._extract_group_labels(
            features=synthetic_features,
            labels=synthetic_labels,
            protected_attribute=protected_attribute,
        )

        all_groups = sorted(set(real_groups.keys()) | set(synthetic_groups.keys()))

        # 1. KL Divergence of group distribution
        kl_divergence = self._compute_kl_divergence(
            real_groups=real_groups,
            synthetic_groups=synthetic_groups,
            all_groups=all_groups,
            real_total=len(real_labels),
            synthetic_total=len(synthetic_labels),
        )

        # 2. Label rate disparity per group
        label_rate_disparity, group_stats = self._compute_label_rate_disparity(
            real_groups=real_groups,
            synthetic_groups=synthetic_groups,
            all_groups=all_groups,
        )

        # 3. Amplification factor (disparate impact comparison)
        amplification_factor = self._compute_amplification_factor(
            real_groups=real_groups,
            synthetic_groups=synthetic_groups,
        )

        logger.info(
            "Synthetic bias amplification check complete",
            protected_attribute=protected_attribute,
            kl_divergence=kl_divergence,
            label_rate_disparity=label_rate_disparity,
            amplification_factor=amplification_factor,
            n_groups=len(all_groups),
        )

        return {
            "kl_divergence": round(kl_divergence, 6),
            "label_rate_disparity": round(label_rate_disparity, 6),
            "amplification_factor": round(amplification_factor, 6),
            "group_stats": group_stats,
        }

    def _extract_group_labels(
        self,
        features: list[dict[str, Any]],
        labels: list[int],
        protected_attribute: str,
    ) -> dict[str, dict[str, Any]]:
        """Extract per-group counts and positive label rates.

        Args:
            features: Feature dicts.
            labels: Binary labels.
            protected_attribute: Column name to group by.

        Returns:
            Dict mapping group_value_string -> {"count": int, "positive": int,
            "positive_rate": float}.
        """
        group_data: dict[str, dict[str, Any]] = {}
        for feat, label in zip(features, labels):
            group_val = str(feat.get(protected_attribute, "_unknown"))
            if group_val not in group_data:
                group_data[group_val] = {"count": 0, "positive": 0}
            group_data[group_val]["count"] += 1
            group_data[group_val]["positive"] += label

        for group_val, data in group_data.items():
            count = data["count"]
            data["positive_rate"] = data["positive"] / count if count > 0 else 0.0

        return group_data

    def _compute_kl_divergence(
        self,
        real_groups: dict[str, dict[str, Any]],
        synthetic_groups: dict[str, dict[str, Any]],
        all_groups: list[str],
        real_total: int,
        synthetic_total: int,
    ) -> float:
        """Compute KL divergence of group distributions: real || synthetic.

        A high KL divergence indicates the generator altered the demographic
        composition of the data (more or fewer samples from certain groups).

        Args:
            real_groups: Per-group data from real dataset.
            synthetic_groups: Per-group data from synthetic dataset.
            all_groups: Sorted list of all group values across both datasets.
            real_total: Total number of real samples.
            synthetic_total: Total number of synthetic samples.

        Returns:
            KL divergence scalar (nats). Returns 0.0 if either distribution is empty.
        """
        if real_total == 0 or synthetic_total == 0:
            return 0.0

        epsilon = 1e-10
        real_dist = np.array(
            [real_groups.get(g, {}).get("count", 0) / real_total + epsilon for g in all_groups]
        )
        synthetic_dist = np.array(
            [synthetic_groups.get(g, {}).get("count", 0) / synthetic_total + epsilon for g in all_groups]
        )

        # Normalise
        real_dist = real_dist / real_dist.sum()
        synthetic_dist = synthetic_dist / synthetic_dist.sum()

        kl = float(np.sum(rel_entr(real_dist, synthetic_dist)))
        return max(0.0, kl)

    def _compute_label_rate_disparity(
        self,
        real_groups: dict[str, dict[str, Any]],
        synthetic_groups: dict[str, dict[str, Any]],
        all_groups: list[str],
    ) -> tuple[float, list[dict[str, Any]]]:
        """Compute the maximum absolute label rate difference across groups.

        For each group, computes abs(real_positive_rate - synthetic_positive_rate).
        Returns the maximum across all groups as the disparity signal.

        Args:
            real_groups: Per-group data from real dataset.
            synthetic_groups: Per-group data from synthetic dataset.
            all_groups: All group values.

        Returns:
            Tuple of (max_disparity_float, list_of_group_stat_dicts).
        """
        group_stats: list[dict[str, Any]] = []
        disparities: list[float] = []

        for group in all_groups:
            real_data = real_groups.get(group, {"count": 0, "positive": 0, "positive_rate": 0.0})
            synthetic_data = synthetic_groups.get(group, {"count": 0, "positive": 0, "positive_rate": 0.0})

            real_rate: float = real_data.get("positive_rate", 0.0)
            synthetic_rate: float = synthetic_data.get("positive_rate", 0.0)
            disparity = abs(real_rate - synthetic_rate)
            disparities.append(disparity)

            group_stats.append({
                "group_value": group,
                "real_count": real_data.get("count", 0),
                "synthetic_count": synthetic_data.get("count", 0),
                "real_positive_rate": round(real_rate, 6),
                "synthetic_positive_rate": round(synthetic_rate, 6),
            })

        max_disparity = max(disparities) if disparities else 0.0
        return max_disparity, group_stats

    def _compute_amplification_factor(
        self,
        real_groups: dict[str, dict[str, Any]],
        synthetic_groups: dict[str, dict[str, Any]],
    ) -> float:
        """Compute the bias amplification factor.

        Measures disparate impact in both datasets and returns the ratio
        synthetic_di / real_di. Values > 1.0 indicate the synthetic data
        has worse (lower) disparate impact than the real data, meaning the
        generator amplified existing demographic disparities.

        Disparate impact is computed as min_group_rate / max_group_rate.
        A value of 1.0 means perfect parity; lower values mean more disparity.
        The amplification factor inverts this: synthetic_di / real_di, so
        a factor > 1.0 means synthetic DI is worse (more biased).

        Args:
            real_groups: Per-group data from real dataset.
            synthetic_groups: Per-group data from synthetic dataset.

        Returns:
            Amplification factor (float >= 0). Returns 1.0 if either dataset
            has only one group or zero positive rates.
        """
        def disparate_impact(groups: dict[str, dict[str, Any]]) -> float:
            """Compute min/max disparate impact for a group distribution."""
            rates = [data.get("positive_rate", 0.0) for data in groups.values() if data.get("count", 0) > 0]
            if len(rates) < 2:
                return 1.0
            max_rate = max(rates)
            min_rate = min(rates)
            return min_rate / max_rate if max_rate > 0 else 1.0

        real_di = disparate_impact(real_groups)
        synthetic_di = disparate_impact(synthetic_groups)

        if real_di <= 0:
            return 1.0

        # Lower DI = more bias. Amplification factor = real_di / synthetic_di.
        # If synthetic_di < real_di (more bias), factor > 1.0 (amplification).
        # If synthetic_di >= real_di (less or equal bias), factor <= 1.0 (no amplification).
        amplification_factor = real_di / synthetic_di if synthetic_di > 0 else float("inf")
        return min(amplification_factor, 100.0)  # Cap at 100x for readability
